/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;
import java.util.List;
import persistencia.ControladorPersistencia;
import logica.Instituto;
import logica.Curso;
import logica.EdicionCurso;
import logica.Estudiante;
import javax.swing.*;

/**
 *
 * @author Nicolás
 */
public class InscripcionAEdicionDeCursoInternalFrame extends javax.swing.JInternalFrame {

    
    private ControladorPersistencia cp;
    
    public InscripcionAEdicionDeCursoInternalFrame(ControladorPersistencia cp) {
        initComponents();
        estudianteSeleccionadoTXT.setVisible(false);
        this.cp = cp;
        
        setSize(750, 500);
        cargarInstitutos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        EdicionVigenteTXT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        estudianteSeleccionadoTXT = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Inscripción a Edicion de Curso");

        jLabel1.setText("Instituto:");

        jComboBox1.addActionListener(this::jComboBox1SeleccionoInstituto);

        jLabel2.setText("Curso: ");

        jComboBox2.addActionListener(this::jComboBox2SeleccionoCursoDeInstituto);

        jLabel4.setText("Edición:");

        EdicionVigenteTXT.setEditable(false);
        EdicionVigenteTXT.addActionListener(this::EdicionVigenteTXTActionPerformed);

        jButton1.setText("Seleccionar Estudiante");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel6.setText("Estudiante: ");

        estudianteSeleccionadoTXT.setText("jLabel7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EdicionVigenteTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(estudianteSeleccionadoTXT)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(EdicionVigenteTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(estudianteSeleccionadoTXT))
                .addContainerGap(202, Short.MAX_VALUE))
        );

        estudianteSeleccionadoTXT.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void cargarInstitutos() {
        jComboBox1.removeAllItems();

        List<Instituto> institutos = cp.obtenerInstitutos();

        for (Instituto instituto : institutos) {
        jComboBox1.addItem(instituto);
        }
    }
    
    private void jComboBox1SeleccionoInstituto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1SeleccionoInstituto
        // TODO add your handling code here:
        Instituto institutoSeleccionado =
            (Instituto) jComboBox1.getSelectedItem();

    if (institutoSeleccionado == null) {
        return;
    }

    jComboBox2.removeAllItems();
    //jComboBox3.removeAllItems();

    for (Curso curso : institutoSeleccionado.getCursos()) {
        jComboBox2.addItem(curso);
    }
    }//GEN-LAST:event_jComboBox1SeleccionoInstituto

    private void jComboBox2SeleccionoCursoDeInstituto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2SeleccionoCursoDeInstituto
        // TODO add your handling code here:
        Curso cursoSeleccionado = (Curso) jComboBox2.getSelectedItem();

    if (cursoSeleccionado == null) {
        return;
    }

    EdicionVigenteTXT.setText("No hay edición vigente");

    for (EdicionCurso edicion : cursoSeleccionado.getEdiciones()) {
        if (edicion.esVigente()) {
          EdicionVigenteTXT.setText(edicion.getNombre());
            break;
    }
}
        
    
    }//GEN-LAST:event_jComboBox2SeleccionoCursoDeInstituto

    private void EdicionVigenteTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdicionVigenteTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdicionVigenteTXTActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        List<Estudiante> estudiantes = cp.obtenerEstudiantes();

    if (estudiantes.isEmpty()) {
        JOptionPane.showMessageDialog(
            this,
            "No hay estudiantes registrados."
        );
        return;
    }

    Estudiante seleccionado = (Estudiante) JOptionPane.showInputDialog(
        this,
        "Seleccione un estudiante:",
        "Estudiantes",
        JOptionPane.PLAIN_MESSAGE,
        null,
        estudiantes.toArray(),
        estudiantes.get(0)
    );

    if (seleccionado != null) {
        estudianteSeleccionadoTXT.setText(
            seleccionado.getNombre()
        );
    }
    
    if (seleccionado != null) {
    estudianteSeleccionadoTXT.setText(seleccionado.getNombre());
    estudianteSeleccionadoTXT.setVisible(true);
    }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EdicionVigenteTXT;
    private javax.swing.JLabel estudianteSeleccionadoTXT;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<Instituto> jComboBox1;
    private javax.swing.JComboBox<Curso> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
