/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;


import java.util.List;
import java.util.ArrayList;
import logica.ControladorUsuario;

/**
 *
 * @author adrie
 */
public class InternalConsultaUsuario extends javax.swing.JInternalFrame {

    private ControladorUsuario control;
    
    public InternalConsultaUsuario(ControladorUsuario control) {
        initComponents();
        this.control = control;
        
        cargarUsuariosEnCombo();
    }

    
    
    
    private void cargarUsuariosEnCombo() {
    cmbUsuarios.removeAllItems();
    List<String> nickname = control.listarNicknamesUsuarios();
    
    for (String nick : nickname) {
        cmbUsuarios.addItem(nick);
    }
    
    // Dejamos la selección vacía al principio para que no cargue datos por accidente
    cmbUsuarios.setSelectedIndex(-1); 
}
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbUsuarios = new javax.swing.JComboBox<>();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtMail = new javax.swing.JTextField();
        txtFechaNac = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCursosEdiciones = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstProgramas = new javax.swing.JList<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setText("Seleccionar Usuario");

        cmbUsuarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbUsuarios.addActionListener(this::cmbUsuariosActionPerformed);

        txtNombre.setEditable(false);

        txtApellido.setEditable(false);

        txtMail.setEditable(false);

        txtFechaNac.setEditable(false);

        lstCursosEdiciones.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstCursosEdiciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstCursosEdicionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstCursosEdiciones);

        lstProgramas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstProgramas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstProgramasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstProgramas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNombre)
                                .addComponent(txtApellido)
                                .addComponent(txtMail)
                                .addComponent(txtFechaNac, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(cmbUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUsuariosActionPerformed
        // Evitamos errores si el combo está vacío (por ejemplo al borrar los items)
    if (cmbUsuarios.getSelectedItem() == null) {
        return; 
    }

    String nicknameSeleccionado = cmbUsuarios.getSelectedItem().toString();
    
    // Le pedimos al controlador el usuario
   logica.Usuario u = control.obtenerUsuarioPorNickname(nicknameSeleccionado);
    
    if (u != null) {
        // 1. Llenamos los datos básicos (Tus JTextFields)
        txtNombre.setText(u.getNombre());
        txtApellido.setText(u.getApellido());
        txtMail.setText(u.getMail());
        if (u.getFechaNacimiento() != null) {
                java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
                txtFechaNac.setText(sdf.format(u.getFechaNacimiento()));
            } else {
                txtFechaNac.setText("No registrada");
            } 
        
        // 2. Diferenciamos si es Docente o Estudiante
        // Para hacer esto, en Java usamos "instanceof"
        if (u instanceof logica.Docente) {
            logica.Docente doc = (logica.Docente) u;
            javax.swing.DefaultListModel<String> modeloCursos = new javax.swing.DefaultListModel<>();
            javax.swing.DefaultListModel<String> modeloProgramas = new javax.swing.DefaultListModel<>();

            if (doc.getCursosAsignados() != null) {
                    for (String nombreCurso : doc.getCursosAsignados()) {
                        modeloCursos.addElement(nombreCurso);
                    }
                }
                
                if (doc.getProgramasAsignados() != null) {
                    for (String nombrePrograma : doc.getProgramasAsignados()) {
                        modeloProgramas.addElement(nombrePrograma);
                    }
                }

            lstCursosEdiciones.setModel(modeloCursos);
            lstProgramas.setModel(modeloProgramas);
        }else if (u instanceof logica.Estudiante){
            logica.Estudiante est = (logica.Estudiante) u;
            javax.swing.DefaultListModel<String> modeloEdiciones = new javax.swing.DefaultListModel<>();
            javax.swing.DefaultListModel<String> modeloProgramasEst = new javax.swing.DefaultListModel<>();
            if (est.getEdicionesInscriptas() != null) {
                    for (String nombreEdicion : est.getEdicionesInscriptas()) {
                        modeloEdiciones.addElement(nombreEdicion);
                    }
                }

            lstCursosEdiciones.setModel(modeloEdiciones);
            lstProgramas.setModel(modeloProgramasEst);
        }
        
    }
    }//GEN-LAST:event_cmbUsuariosActionPerformed

    private void lstCursosEdicionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstCursosEdicionesMouseClicked
        // Verificamos que sea un doble clic
    if (evt.getClickCount() == 2) {
        // Obtenemos el texto del elemento al que le hicieron clic
        String seleccionado = lstCursosEdiciones.getSelectedValue();
        
        if (seleccionado != null) {
            // Instanciamos el controlador que pide la ventana
                persistencia.ControladorPersistencia cp = new persistencia.ControladorPersistencia();
                
                // Creamos la ventana con la clase
                ConsultaEdicionDeCursoInternalFrame ventanaCurso = new ConsultaEdicionDeCursoInternalFrame(cp);
                
                // La agregamos al escritorio principal y la mostramos
                this.getDesktopPane().add(ventanaCurso); 
                ventanaCurso.setVisible(true);
                ventanaCurso.toFront(); // Trae la ventana al frente
            }
    }
    }//GEN-LAST:event_lstCursosEdicionesMouseClicked

    private void lstProgramasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstProgramasMouseClicked
        // Verificamos que sea un doble clic
    if (evt.getClickCount() == 2) {
        // Obtenemos el texto del elemento al que le hicieron clic
        String seleccionado = lstProgramas.getSelectedValue();
        
        if (seleccionado != null) {
            // Instanciamos el controlador
                persistencia.ControladorPersistencia cp = new persistencia.ControladorPersistencia();
                
                // Creamos la ventana de Programa de Formación
                ConsultaProgramaFormacionInternalFrame ventanaPrograma = new ConsultaProgramaFormacionInternalFrame(cp);
                
                // La agregamos al escritorio principal y la mostramos
                this.getDesktopPane().add(ventanaPrograma);
                ventanaPrograma.setVisible(true);
                ventanaPrograma.toFront(); // Trae la ventana al frente
            }
    }
    }//GEN-LAST:event_lstProgramasMouseClicked


    
    
    
    
    
    
    
    
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstCursosEdiciones;
    private javax.swing.JList<String> lstProgramas;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtFechaNac;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
