/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;


import javax.swing.*;
import persistencia.ControladorPersistencia;

/**
 *
 * @author elizeth
 */
public class PrincipalFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PrincipalFrame.class.getName());

    // 1. El contenedor virtual donde flotarán los JInternalFrame
    private void abrirInternalFrame(JInternalFrame frame) {

            // Evitar ventanas duplicadas
        for (JInternalFrame abierto : jDesktopPane1.getAllFrames()) {

            if (abierto.getClass().equals(frame.getClass())) {

                try {
                    abierto.setSelected(true);
                    abierto.toFront();
                } catch (java.beans.PropertyVetoException e) {
                    e.printStackTrace();
                }

                return;
            }
        }

        // Agregar la ventana
        jDesktopPane1.add(frame);

        // Ajustar tamaño
        frame.pack();

        // Centrar
        int x = (jDesktopPane1.getWidth() - frame.getWidth()) / 2;
        int y = (jDesktopPane1.getHeight() - frame.getHeight()) / 2;

        frame.setLocation(Math.max(x, 0), Math.max(y, 0));

        frame.setVisible(true);

        try {
            frame.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
            e.printStackTrace();
        }
    }
    // 2. La instancia de la lógica/persistencia
    private ControladorPersistencia controlPersistencia;

    public PrincipalFrame() {
        initComponents();

        controlPersistencia = new ControladorPersistencia();

        setTitle("edEXT - Plataforma Educativa");
        setLocationRelativeTo(null);

        // Apariencia del escritorio
        jDesktopPane1.setBackground(new java.awt.Color(245, 247, 250));

        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

 

    // Método Main para iniciar la aplicación
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            PrincipalFrame ventanaPrincipal = new PrincipalFrame();
            ventanaPrincipal.setVisible(true);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSpinner1 = new javax.swing.JSpinner();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuAgregarCursoProg = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        menuConsultaProg = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        jMenu1.setText("Registros");

        menuAgregarCursoProg.setText("Agregar Curso a Programa");
        menuAgregarCursoProg.addActionListener(this::menuAgregarCursoProgActionPerformed);
        jMenu1.add(menuAgregarCursoProg);

        jMenuItem6.setText("Inscripcion a Edicion de Curso");
        jMenuItem6.addActionListener(this::jMenuItem6ActionPerformed);
        jMenu1.add(jMenuItem6);

        jMenuItem7.setText("Alta de Programa de Formacion");
        jMenuItem7.addActionListener(this::jMenuItem7ActionPerformed);
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        menuConsultaProg.setText("Consultas");

        jMenuItem5.setText("Consulta Programa de Formacion");
        jMenuItem5.addActionListener(this::jMenuItem5ActionPerformed);
        menuConsultaProg.add(jMenuItem5);

        jMenuItem4.setText("Consulta de Edicion de Curso");
        jMenuItem4.addActionListener(this::jMenuItem4ActionPerformed);
        menuConsultaProg.add(jMenuItem4);

        jMenuBar1.add(menuConsultaProg);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAgregarCursoProgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgregarCursoProgActionPerformed
        // TODO add your handling code here:
        abrirInternalFrame(new AgregarCursoAProgramaInternalFrame(controlPersistencia));
    }//GEN-LAST:event_menuAgregarCursoProgActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        abrirInternalFrame(new ConsultaProgramaFormacionInternalFrame(controlPersistencia));
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:

        abrirInternalFrame(new ConsultaEdicionDeCursoInternalFrame(controlPersistencia));

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        abrirInternalFrame(new InscripcionAEdicionDeCursoInternalFrame(controlPersistencia));
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        abrirInternalFrame(new CrearProgramaDeFormacionInternalFrame(controlPersistencia));
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JMenuItem menuAgregarCursoProg;
    private javax.swing.JMenu menuConsultaProg;
    // End of variables declaration//GEN-END:variables
}
