/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;


import javax.swing.SwingUtilities;
import persistencia.ControladorPersistencia;

/**
 *
 * @author elizeth
 */
public class PrincipalFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PrincipalFrame.class.getName());

    // 1. El contenedor virtual donde flotarán los JInternalFrame

    // 2. La instancia de la lógica/persistencia
    private ControladorPersistencia controlPersistencia;

    public PrincipalFrame() {
    initComponents();

    controlPersistencia = new ControladorPersistencia();

    setTitle("Plataforma Educativa - edEXT");
    setLocationRelativeTo(null);
}

 

    // Método Main para iniciar la aplicación
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            PrincipalFrame ventanaPrincipal = new PrincipalFrame();
            ventanaPrincipal.setVisible(true);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSpinner1 = new javax.swing.JSpinner();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuAgregarCursoProg = new javax.swing.JMenuItem();
        menuConsultaProg = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        jMenu1.setText("Registros");

        menuAgregarCursoProg.setText("Agregar Curso a Programa");
        menuAgregarCursoProg.addActionListener(this::menuAgregarCursoProgActionPerformed);
        jMenu1.add(menuAgregarCursoProg);

        jMenuBar1.add(jMenu1);

        menuConsultaProg.setText("Consultas");

        jMenuItem5.setText("Consulta Programa de Formacion");
        jMenuItem5.addActionListener(this::jMenuItem5ActionPerformed);
        menuConsultaProg.add(jMenuItem5);

        jMenuItem4.setText("Consulta de Edicion de Curso");
        jMenuItem4.addActionListener(this::jMenuItem4ActionPerformed);
        menuConsultaProg.add(jMenuItem4);

        jMenuBar1.add(menuConsultaProg);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAgregarCursoProgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgregarCursoProgActionPerformed
        // TODO add your handling code here:
        AgregarCursoAProgramaInternalFrame iframe = new AgregarCursoAProgramaInternalFrame(controlPersistencia);
        jDesktopPane1.add(iframe);
        iframe.setVisible(true);
    }//GEN-LAST:event_menuAgregarCursoProgActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        ConsultaProgramaFormacionInternalFrame iframe = new ConsultaProgramaFormacionInternalFrame(controlPersistencia);
        jDesktopPane1.add(iframe);
        iframe.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:

    ConsultaEdicionDeCursoInternalFrame iframe = new ConsultaEdicionDeCursoInternalFrame(controlPersistencia);

    jDesktopPane1.add(iframe);
    iframe.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JMenuItem menuAgregarCursoProg;
    private javax.swing.JMenu menuConsultaProg;
    // End of variables declaration//GEN-END:variables
}
