/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

/**
 *
 * @author elizeth
 */

//import Entities.ProgramaFormacion;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.util.List;
import persistencia.ControladorPersistencia;

public class AgregarCursoAProgramaInternalFrame extends javax.swing.JInternalFrame {

    
    public AgregarCursoAProgramaInternalFrame() {
        initComponents();
    }

    private JComboBox<String> cbProgramas;
    private JComboBox<String> cbCursos;
    private JButton btnAceptar;
    private JButton btnCancelar;
    
    private ControladorPersistencia controlPersistencia;

    public AgregarCursoAProgramaInternalFrame(ControladorPersistencia controlPersistencia) {
        this.controlPersistencia = controlPersistencia;

        setTitle("Agregar Curso a Programa de Formación");
        setClosable(true);
        setMaximizable(true);
        setIconifiable(true);
        setSize(400, 220);

        initGUI();
        cargarCombos();
    }

    private void initGUI() {
        JPanel panel = new JPanel(new GridLayout(3, 2, 10, 10));
        panel.setBorder(BorderFactory.createEmptyBorder(15, 15, 15, 15));

        panel.add(new JLabel("Programa de Formación:"));
        cbProgramas = new JComboBox<>();
        panel.add(cbProgramas);

        panel.add(new JLabel("Curso a integrar:"));
        cbCursos = new JComboBox<>();
        panel.add(cbCursos);

        btnAceptar = new JButton("Aceptar");
        btnCancelar = new JButton("Cancelar");

        panel.add(btnAceptar);
        panel.add(btnCancelar);

        add(panel);

        // Listeners
        btnAceptar.addActionListener((ActionEvent e) -> ejecutarAgregar());
        btnCancelar.addActionListener((ActionEvent e) -> dispose());
    }

    private void cargarCombos() {
        try {
            cbProgramas.removeAllItems();
            List<String> programas = controlPersistencia.listarNombresProgramas();
            for (String prog : programas) {
                cbProgramas.addItem(prog);
            }

            // Asumiendo un método para obtener nombres de cursos en la controladora
            cbCursos.removeAllItems();
            // List<String> cursos = controlPersistencia.listarNombresCursos();
            // for (String c : cursos) cbCursos.addItem(c);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void ejecutarAgregar() {
        String progSeleccionado = (String) cbProgramas.getSelectedItem();
        String cursoSeleccionado = (String) cbCursos.getSelectedItem();

        if (progSeleccionado == null || cursoSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un programa y un curso.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            controlPersistencia.agregarCursoAPrograma(progSeleccionado, cursoSeleccionado);
            JOptionPane.showMessageDialog(this, "Curso agregado al Programa de Formación exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
