/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import java.awt.event.ActionEvent;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.SwingUtilities;
import persistencia.ControladorPersistencia;

/**
 *
 * @author elizeth
 */
public class PrincipalFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PrincipalFrame.class.getName());

    // 1. El contenedor virtual donde flotarán los JInternalFrame
    private JDesktopPane desktopPane;

    // 2. La instancia de la lógica/persistencia
    private ControladorPersistencia controlPersistencia;

    public PrincipalFrame() {
        // Inicializar la controladora de persistencia
        controlPersistencia = new ControladorPersistencia();
        // Configuración básica de la ventana principal
        setTitle("Plataforma Educativa - edEXT");
        setSize(1024, 768);
        setLocationRelativeTo(null); // Centrar en pantalla
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        // Crear e integrar el JDesktopPane
        desktopPane = new JDesktopPane();
        this.setContentPane(desktopPane);

        // Construir el menú superior
        construirMenu();
    }

    private void construirMenu() {
        JMenuBar menuBar = new JMenuBar();

        // --- MENÚ REGISTROS ---
        JMenu menuRegistros = new JMenu("Registros");
        
        JMenuItem itemAgregarCursoProg = new JMenuItem("Agregar Curso a Programa");
        menuRegistros.add(itemAgregarCursoProg);

        // --- MENÚ CONSULTAS ---
        JMenu menuConsultas = new JMenu("Consultas");
        
        JMenuItem itemConsultaProg = new JMenuItem("Consulta de Programa de Formación");
        menuConsultas.add(itemConsultaProg);

        // Agregar menús a la barra
        menuBar.add(menuRegistros);
        menuBar.add(menuConsultas);
        this.setJMenuBar(menuBar);

        
        // CONFIGURACIÓN DE EVENTOS (LISTENERS)
       

        // Acción: Abrir "Agregar Curso a Programa"
        itemAgregarCursoProg.addActionListener((ActionEvent e) -> {
            AgregarCursoAProgramaInternalFrame iframe = 
                new AgregarCursoAProgramaInternalFrame(controlPersistencia);
            
            desktopPane.add(iframe); // 1. Agregar al escritorio interno
            iframe.setVisible(true); // 2. Hacerlo visible
        });

        // Acción: Abrir "Consulta de Programa de Formación"
        itemConsultaProg.addActionListener((ActionEvent e) -> {
            ConsultaProgramaFormacionInternalFrame iframe = 
                new ConsultaProgramaFormacionInternalFrame(controlPersistencia);
            
            desktopPane.add(iframe); // 1. Agregar al escritorio interno
            iframe.setVisible(true); // 2. Hacerlo visible
        });
    }

    // Método Main para iniciar la aplicación
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            PrincipalFrame ventanaPrincipal = new PrincipalFrame();
            ventanaPrincipal.setVisible(true);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
