/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.tarea_1_prog_app;

/**
 *
 * @author adrie
 */
public class InternalAltaUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalAltaUsuario
     */
    private ControladorUsuario control;
    
    public InternalAltaUsuario() {
        initComponents();
    }
    
    
    public InternalAltaUsuario(ControladorUsuario control) {
    initComponents();
    this.control = control;

    // Configuración de rangos para la Fecha de Nacimiento (Día 1-31, Mes 1-12, Año 1900-2026)
    spnDia.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
    spnMes.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
    spnAno.setModel(new javax.swing.SpinnerNumberModel(2000, 1900, 2026, 1));

    // Estado inicial de selección de Instituto
    cmbInstituto.setEnabled(false);
    cargarInstitutos();
}

    private void cargarInstitutos() {
    cmbInstituto.removeAllItems();
    cmbInstituto.addItem("Seleccione un Instituto...");
    // Ejemplo de carga: reemplaza por tu llamada a la BD o lista de institutos
    cmbInstituto.addItem("INCO - Instituto de Computación");
    cmbInstituto.addItem("IMERL - Instituto de Matemática");
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNickname = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        spnDia = new javax.swing.JSpinner();
        spnMes = new javax.swing.JSpinner();
        spnAno = new javax.swing.JSpinner();
        cmbInstituto = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        chkDocente = new javax.swing.JCheckBox();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Alta de Usuario");
        setToolTipText("");

        jLabel1.setText("Nickname:");

        jLabel2.setText("Ingrese los siguientes datos");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Apellido:");

        jLabel5.setText("Correo:");

        txtNickname.addActionListener(this::txtNicknameActionPerformed);

        txtNombre.addActionListener(this::txtNombreActionPerformed);

        jLabel7.setText("Fecha de nacimiento");

        cmbInstituto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbInstituto.addActionListener(this::cmbInstitutoActionPerformed);

        jLabel8.setText("Instituto");

        chkDocente.setText("Es docente");
        chkDocente.addActionListener(this::chkDocenteActionPerformed);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(this::btnAceptarActionPerformed);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(115, 115, 115))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbInstituto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spnDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                .addComponent(txtApellido)
                                .addComponent(txtNombre)
                                .addComponent(txtNickname)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkDocente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5))
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(spnDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(spnMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(spnAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbInstituto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(chkDocente)
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAceptar)
                            .addComponent(btnCancelar))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbInstitutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbInstitutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbInstitutoActionPerformed

    private void chkDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDocenteActionPerformed
        boolean esDocente = chkDocente.isSelected();
    cmbInstituto.setEnabled(esDocente);
    if (!esDocente) {
        cmbInstituto.setSelectedIndex(0);
    }
    }//GEN-LAST:event_chkDocenteActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        
    // 1. Obtención de datos de texto
    String nickname = txtNickname.getText().trim();
    String nombre = txtNombre.getText().trim();
    String apellido = txtApellido.getText().trim();
    String correo = txtCorreo.getText().trim();

    // 2. Obtención de fecha desde los 3 JSpinner
    int dia = (int) spnDia.getValue();
    int mes = (int) spnMes.getValue();
    int ano = (int) spnAno.getValue();
    String fechaNac = dia + "/" + mes + "/" + ano;

    // 3. Validar campos de texto requeridos
    if (nickname.isEmpty() || nombre.isEmpty() || apellido.isEmpty() || correo.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Debe completar todos los campos obligatorios.", 
            "Error de Validación", 
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 4. Validar Instituto si es Docente
    boolean esDocente = chkDocente.isSelected();
    if (esDocente && cmbInstituto.getSelectedIndex() <= 0) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Debe seleccionar un Instituto para el docente.", 
            "Error de Selección", 
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 5. Validar Nickname único
    if (control.existeNickname(nickname)) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "El nickname '" + nickname + "' ya existe. Por favor modifíquelo o cancele.", 
            "Nickname Duplicado", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 6. Validar Correo único
    if (control.existeCorreo(correo)) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "El correo '" + correo + "' ya se encuentra registrado.", 
            "Correo Duplicado", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 7. Registro en el sistema
    if (esDocente) {
        String nombreInst = cmbInstituto.getSelectedItem().toString();
        Instituto inst = new Instituto(nombreInst);
        control.registrarDocente(nickname, correo, nombre, apellido, fechaNac, inst);
    } else {
        control.registrarEstudiante(nickname, correo, nombre, apellido, fechaNac);
    }

    javax.swing.JOptionPane.showMessageDialog(this, 
        "Usuario registrado exitosamente.", 
        "Éxito", 
        javax.swing.JOptionPane.INFORMATION_MESSAGE);

    limpiarFormulario();

    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtNicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNicknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNicknameActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose(); // Cierra la ventana interna actual
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed


    private void limpiarFormulario() {
    txtNickname.setText("");
    txtNombre.setText("");
    txtApellido.setText("");
    txtCorreo.setText("");
    spnDia.setValue(1);
    spnMes.setValue(1);
    spnAno.setValue(2000);
    chkDocente.setSelected(false);
    cmbInstituto.setSelectedIndex(0);
    cmbInstituto.setEnabled(false);
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JCheckBox chkDocente;
    private javax.swing.JComboBox<String> cmbInstituto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSpinner spnAno;
    private javax.swing.JSpinner spnDia;
    private javax.swing.JSpinner spnMes;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNickname;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
